### ISSUE TITLE
Export file feature should provide .avsc format for Avro schemas

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1234]
## Background
We have added support of avro format import to Menas. Now it is time to add avro file format for the export file feature. Currently, people would get `.cob` as default in case of avro schema.

## Feature
1. Add avro format to export file feature
2. Add a general format. Like `.txt` if no format is matched

## Example
When I export spark struck file I get `.json`
When I export cobol copybook I get `.cob`
When I export avro schema original file it should be `avsc`

## Additional Info
Check Menas's `ui/components/schema/schemaDetail.controller.js` method  `_getFileExtension`

**Comment by dk1844** [comment]
> ## Example
> When I export spark struck file I get `.json`
> When I export cobol copybook I get `.cob`
> When I export avro schema original file it should be `avsc`

A slight problem with this is that the **type of schema of the original attachment** is not really saved at the moment (avsc schema files either have a default mimetype `application/octet-stream` (shared with `cob`) or they have `application/vnd.schemaregistry.v1+json` if they come from the Schema registry. The _Export File_ feature's type is based on the saved mimetype, which is incorrect - that is why we are getting `.cob` for an `.avsc` content. This can have an adverse effect on the already existing AVSC attachments when changed.

I see multiple opinions on how to approach:

1. add a new field in menas persistence to take a note of the enum-like schema type (this would work for forward, but not for the existing data.
2. change the mime-type saved for AVSC to, say, `application/avro-json` (regardless of where it is coming from)
3. somehow derive the type from the binary content field? (may get complicated)

With 1) and 2), some sort of heuristic-based migration script can be used to derive the missing information, e.g.:
 - original filename ending with *.avsc -> AVSC type
 - mimetype `application/vnd.schemaregistry.v1+json` -> AVSC type (because the schema registry can only hold AVSC).


I think 1) is the easiest while 2) is the most correct solution, because there should not be multiple mimetypes for the same file type (provided we chose the correct mimetype for AVSC)...

---

Is it even ok to be using `application/avro-json`? [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) does not even list any avro related entries.
I have found various mentions and variation on what the "correct" mimetypes for AVSC might be, namely in
 - [here](https://github.com/vkrava4/avro-converter/blob/master/README.md) (`application/avro-json`)
 - [here](https://github.com/Talend/components/blob/master/services/components-api-service-rest/src/main/java/org/talend/components/service/rest/RuntimesController.java) (`application/x-avro-json`)
 - [here](https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.M1/reference/html/contenttypemanagement.html) (`application/avro`)

Maybe the least wrong mimetype would be using `application/vnd.schemaregistry.v1+json`, since Schema Registry already established it.

Any thoughts? @Zejnilovic @yruslan @benedeki

**Comment by dk1844** [comment]
Release notes:
AVSC typed schema can be exported as same other types.

**Comment by dk1844** [comment]
#1350 fixes the behavior for any future attachments made, the following mongo script can be used to fix any existing db content, should it exist:
```javascript
db.getCollection('attachment_v1').updateMany(
    {"filename" : { $regex: "\.avsc$" }},
    {$set : {"fileMIMEType" : "application/vnd.schemaregistry.v1+json"}}
)
```
