### ISSUE TITLE
UI Changes for Dataset properties - pilot property: Data Classification

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1571]
## Background
Dataset properties is a map attached to a Dataset.
The keys of the map are defined on application setup level. They are common to all Datasets of the deployment.
The values then are entered by users and are specific per each Dataset.

## Feature
Implement the UI changes to display properties and the control for selection from the list for pilot _Data Classification_ property.
Including the API calls for dealing with the properties.

**Comment by Zejnilovic** [comment]
Next step: Will add analysis and needs

**Comment by Zejnilovic** [comment]
We have a new Properties API. One is for setting the Property Definitions and one is to add properties to Datasets. This issue is about adding the properties do Dataset. Setting properties on Dataset should come with the Create/Edit dialogue window. But we need to keep in mind that properties will be in later versions added to all versionedModel entities (schema, mapping table)

All property definitions can be found at `BASE_URL/api/properties/datasets`. This returns an array of PropertyDefinitions. The latest version of each. Here we are interested in `$[*].propertyType,essentiality`. That jsonPath would show off the property type and if it is mandatory or not. 

Currently, types are a string or enum. For each of these types, we would have a `display` and `add` fragment. These would be located (presumably) in properties folder `properties` in `/menas/ui/components` and have a similar setup as the ConformanceRules that dynamically load appropriate fragment. 

In Dataset Create/Edit fragments there would be a (presumably) `CustomListItem` that would then invoke appropriate add fragments. to be edited. In Dataset Details appropriate detail fragments.

Behaviour on essentiality:
 - mandatory - needs to be filled in
 - optional - a pop-up warning if the person is sure
 - optional - leave it be

Attributes of String Property type:
 - suggested value (might be empty)

Attributes of Enum Property type
- allowed values
- suggested value (has to be one of the allowed ones)

**Comment by lokm01** [comment]
Release Notes:
[Menas] Implemented the UI changes for dataset properties

**Comment by aaishaosman** [comment]
SECURITY CLASSIFICATION per dataset – selection from dropdown Public, Internal, Confidential, Secret

**Comment by aaishaosman** [comment]
For future…i iwll still define these
CONTENT TYPE per dataset (customer data, transactional etc)
RETENTION per dataset – still figuring out what we need here to help eventually drive data lifecycle management on AWS
GENERAL – per datasets, open text tagging concept to assist with searching etc
