### ISSUE TITLE
Consistent dataset versioning

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#164]
When a user creates a new dataset in Menas it starts with the version 0. But std job cannot take 0 as a dataset version:
 Error: Option --dataset-version must be >0

**Comment by GeorgiChochov** [comment]
It seems the schema is the only entity that actually isn't ready for use when initially created. That is, a `schema` entity is created with version 0 and without an actual spark-schema attached to it, so it's the only one that actually requires an update to version 1 (uploading the schema file) in order to become useable.

I think we can probably start the versioning from 1 on all of the entities, rather than from 0. We can keep the spark-job option for version > 0.
