### ISSUE TITLE
Standartization Job should warn me if schema and data differ

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#203]
## Background
When I have a different name in the schema and in data, I get an error in `errCol` and the data in DataFrame are not found. I would expect a `WARN` message when standardizing.

## Feature
Print a `WARN` message when schema and data differ. Something like
WARN: FIELD1 from Schema not found in Data
WARN: FEILD1 from Data not found in Schema

**Comment by yruslan** [comment]
This is quite a complicated issue. The real problem here is that the data does not have a stable schema beside the one explicitly provided by a user.
- Daily data is split by days and sometimes an uncommon field can be absent on a particular day. 
- Raw data can be in xml or json which require traversing all (or partly) of the data in order to derive a schema since the set of fields can change from a record to record.

At some point it was decided that the schema a user provides is the one we expect and apply. If a schema expects a non-nullable field and it is absent in the data we generate an error. If a field is present in the data, but not in the schema, we just ignore it.

But, as always, this is open to discussions

**Comment by Zejnilovic** [comment]
> This is quite a complicated issue. The real problem here is that the data does not have a stable schema beside the one explicitly provided by a user.
> 
> * Daily data is split by days and sometimes an uncommon field can be absent on a particular day.
> * Raw data can be in xml or json which require traversing all (or partly) of the data in order to derive a schema since the set of fields can change from a record to record.
> 
> At some point it was decided that the schema a user provides is the one we expect and apply. If a schema expects a non-nullable field and it is absent in the data we generate an error. If a field is present in the data, but not in the schema, we just ignore it.
> 
> But, as always, this is open to discussions

If it is by design and has a reason like this, I am cool with it.

**Comment by GeorgiChochov** [comment]
@yruslan makes a good point. I say we either put this in the Icebox for now or close it all together.

**Comment by Zejnilovic** [comment]
In light to #60 I am closing this
