### ISSUE TITLE
Add browser check for Chromium based browsers

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#456]
## Background
We don't have time or the manpower to support other browsers. We are going to only support chromium based ones.

## Feature
Blow up on other browsers

**Comment by benedeki** [comment]
I object against such behavior.
We are already getting to the situation like it was years ago with IE6. Some sites work only in chromium and it's not because it would stick to standards the most. With a feature like this, we just support browser monopoly.
Do we use any special controls or flows that fail in other browsers? Isn't our UX library actually supposed to address these - as one of the reasons to use such a library anyway?

**Comment by Zejnilovic** [comment]
> I object against such behavior.
> We are already getting to the situation like it was years ago with IE6. Some sites work only in chromium and it's not because it would stick to standards the most. With a feature like this, we just support browser monopoly.
> Do we use any special controls or flows that fail in other browsers? Isn't our UX library actually supposed to address these - as one of the reasons to use such a library anyway?

We do have troubles with Edge and Safari of the major browser distributions. Views not updating after you select a first model, only that model updates.

**Comment by lokm01** [comment]
> I object against such behavior.
> We are already getting to the situation like it was years ago with IE6. Some sites work only in chromium and it's not because it would stick to standards the most. With a feature like this, we just support browser monopoly.
> Do we use any special controls or flows that fail in other browsers? Isn't our UX library actually supposed to address these - as one of the reasons to use such a library anyway?

The whole point of this is that the project is developed and tested on chrome(ium) - or at least 95% of it is.

If we don't have time to test using other browsers (and right now we don't) the best thing we can do is to give them a warning at the very least.
