### ISSUE TITLE
Column enceladus_info_date does not respect timezones

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#458]
## Describe the bug
The new column that is written at the end of the DynamicConformance job does not respect timezones. My local timezone is set to Europe/Prague and when the date converts it always subtracts a day so it seems I ran it a day before the data even existed.

## To Reproduce
1. Change your timezone to Europe/Prague
2. Run conformance job
3. output folder date is correct
4. enceladus_info_date is mismatched by a day 

## Expected behaviour
I would expect timezone to be normalized or ignored in this part.

## Additional context
My timezone
```scala
scala> TimeZone.getDefault
res34: java.util.TimeZone = sun.util.calendar.ZoneInfo[id="Europe/Prague",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Prague,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
```

Error traced to _DynamicConformanceJob.scala_ line 110

**Comment by benedeki** [comment]
The reason of the bug was that `SimpleDateFormat` object was created before the `TimeZoneNormalizer` executed its logic. Within the constructor of the `SimpleDateFormat` the current default time zone (at this time equal to system time zone) is bound in, and later used in some flows.

The main solution is in PR #604. 

There's an optional PR #605, which intent is to reduce the chance of a similar problems in future as much as possible. On the other hand, it contains some logic executed on the instantiation of the companion object, which might be considered undesired.
