### ISSUE TITLE
Can we upload all conformation and standardization rules into Menas repository through backend/SQL etc.?

### ISSUE THREAD

**Issue by yparesh** [AbsaOSS/enceladus#593]
Can we upload all conformation and standardization rules into Menas repository through backend/SQL etc.? without using Menas frontend? We have hundreds of rules and don't want to manually enter it in UI which will be time-consuming. Also such automation will be required to promote the  conformation and standardization rules from say Dev to TEST to QA to Prod.

Thanks.

**Comment by Zejnilovic** [comment]
Hi there, sure it is possible to not use Menas front end and upload your rules and models using REST API or you could dump them straight into MongoDB yourself. However, we do not have any scripts for such usecases and therefore you would need to write your own.

Unfortunately, we don't have REST endpoints documentation at the moment as the Enceladus project was released only yesterday. But how REST API works is easily deducible from your network activity while creating a few items. This is also true for the mongo models.

In regards to moving from Dev to TEST or any other phase, since the models here are already going to be in Enceladus's mongo, they are easily manipulated by using mongo queries and moved using mongodump and no further scripting is required.

**Comment by GeorgiChochov** [comment]
Hi there! 

Like @Zejnilovic said, there are ways to do it if you are maintaining your own instances, but no easy way to allow users to do so.

One issue to be aware of when doing `mongodump` from one server and `mongorestore` onto another, is that you might end up with conflicting entries. If a dataset with the same name and version was created separate on both environments, when one is moved onto the other, you'll end up with both of them because mongo does not have `unique key constraints`. This is an issue we need to solve first and is why this promotion should be handled through Menas.

The ability to promote entities from one environment to another is something we definitely want to implement in the near future. I've raised an issue for it (#594), you can subscribe to and follow progress on. We are also planning to make it possible to export and import entity definitions as `json` from the UI (#34), which serves a similar purpose.

I hope this answers your question @yparesh.

**Comment by yparesh** [comment]
@Zejnilović, Thank you for your useful reply. In the long-term, for serious competitiveness, ability to mass upload data might be good to add as many organizations will have something existing that they would like to migrate to Enceladus. REST API can serve that purpose once documented. I have seen some tools in the past that can auto-generate docs for REST API from code. Haven't used any personally.

@Georgi, Thanks for pointing to the caution about mongodump from one server to mongorestore onto another and adding a feature request  (issue #594),

**Comment by GeorgiChochov** [comment]
>  I have seen some tools in the past that can auto-generate docs for REST API from code. Haven't used any personally.

Thanks for the suggestion. Documenting our REST API is something that's been in the back of our mind for a while, but is of very low priority for the time being. I have raised the task for it and we'll eventually get to it #601.

@yparesh If there is nothing else can we consider this closed?

**Comment by yparesh** [comment]
@Georgi, Thanks. I have closed this issue.
