### ISSUE TITLE
Drop (Do not persist) fields that are not registered in schema

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#60]
Do not write parquet file with attributes not registered in the schema, this is usually a symptom where source has attributes, but the schema in the schema repository has not been updated.

Want to use this to ensure owners keep up with schema changes and give control of data distribution for attributes to data owners

**Comment by GeorgiChochov** [comment]
@benedeki @lokm01 Does this task describe the current behaviour of standardizaiton correctly?

**Comment by lokm01** [comment]
Probably still a thing

**Comment by benedeki** [comment]
Yeah, don't recall any removal or filtering of fields in **Standardization**.

**Comment by GeorgiChochov** [comment]
Thanks guys! I've moved this up in the backlog.

**Comment by Zejnilovic** [comment]
We enforce schema so that means that the columns do get dropped. But there is a little problem here (explained at the bottom).

1st picture using schema without one column
![image](https://user-images.githubusercontent.com/17467768/62027445-01a5a600-b1de-11e9-9b9b-dca586d828b9.png)

2nd picture not using schema (inferring it)
![image](https://user-images.githubusercontent.com/17467768/62027494-1c781a80-b1de-11e9-9a01-2a56e0bce2f6.png)

Problem is that when `rawFormat` is `parquet`, we skip schema enforcement. This is in method `prepareDataFrame` of `StandardizationJob.scala`. This is probably because we add `errCol`, `enceladus_info_date`, `enceladus_info_date_string` and `enceladus_info_version`. These columns are not known by the user and might not be reflected in the schema and as such dropped. More about this in #421

**Comment by Zejnilovic** [comment]
I tested it and consulted it with @yruslan 

Schemas are enforced (unused fields not persisted) for every file type. I think that what does this is `StandardizationInterpreter#standardizeDataset`. This works even for complex structures Int in Struct in Array.
