### ISSUE TITLE
Small files problem

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#670]
Figure out how to do automatic repartitioning of output data in order to match the HDFS block size as close as possible => tf. avoid the small files problem

**Comment by DzMakatun** [comment]
This issue is addressed in # 1098.
The main reasons of excessive partitioning are:
- Mismatch between data size and number of total allocated cores (Addressed with DRA)
- Default partitioning in shuffles, resulting in 200 partitions. (Addressed with Adaptive execution , which is now included in default DRA config)

**Comment by DzMakatun** [comment]
resolved in #1362

**Comment by DzMakatun** [comment]
Release notes:
[Overpartitioning (too many tiny files) of output data is resolved by configuring DRA and adaptive execution.]
