### ISSUE TITLE
Migtations module fails to build

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#842]
## Describe the bug
After merging #829 and #778 the build failed on Jenkins with a test in the `migrations` module. This seems to be a mongo-scala-driver serialization issue caused by the upgrade of the driver version.

## To Reproduce
Run `mvn clean package`

## Expected behaviour
The build should pass.

## Error message
```
- Test schema migrates properly and conflicts are resolved *** FAILED ***
  ContinuousMigrationIntegrationSuite.this.datasetExists("TestDataset", 2, "TestSchema1", 2, "TestMT1", 2) was false (ContinuousMigrationIntegrationSuite.scala:63)
```

## Desktop:
 - Version 1.1.0-SNAPSHOT

**Comment by Zejnilovic** [comment]
in `src/main/scala/za/co/absa/enceladus/migrations/continuous/migrate01/DatasetMigrator.scala`
We have a bit of a workaround for serialization:
```scala
      val fixJson = srcDatasetJson.replaceAll("\"jsonClass\" :", "\"_t\" :")
```
for the new mongo we just need to delete the spaces as now the JSONs in string are represented with `"key": "value"` instead of `"key" :"value"`
```scala
      val fixJson = srcDatasetJson.replaceAll("\"jsonClass\":", "\"_t\":")
```

I was trying to solve my failing Jenkins build and ended here. I also found #844 which could be fixed in the same PR.

This is not a full solution imho. We are depending on something unstable.

**Comment by GeorgiChochov** [comment]
Thanks @Zejnilovic

**Comment by GeorgiChochov** [comment]
We have a better regex option, thanks @Zejnilovic
